# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guilds', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild_owner', to='players.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='guildrank',
            unique_together=set([('guild', 'name')]),
        ),
    ]
