# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 09:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, help_text='This email address will be used for account recovery.', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'An account with that username already exists.'}, help_text='Username needs to be from 3 to 30 characters length.\nAllowed characters are: a-z, A-Z, 0-9.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain only english letters and digits.', regex='^[a-zA-Z0-9]+$'), django.core.validators.MinLengthValidator(3)], verbose_name='username'),
        ),
    ]
