# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 14:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170305_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'An account with that username already exists.'}, help_text='Username needs to be from 3 to 30 characters length.\nAllowed characters are: a-z, A-Z, 0-9.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain only english letters and digits.', regex='^[a-zA-Z0-9]+$'), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(30)], verbose_name='username'),
        ),
    ]
