# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:51
from __future__ import unicode_literals

import apps.server.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('permament', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(blank=True, default=apps.server.models.default_ban_length, null=True)),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Cheating'), (2, 'Racist'), (3, 'Swearing'), (4, 'Account sharing'), (5, 'Other')], default=1)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('banned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_bans',
            },
        ),
        migrations.CreateModel(
            name='IPAddressBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('permament', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(blank=True, default=apps.server.models.default_ban_length, null=True)),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Cheating'), (2, 'Racist'), (3, 'Swearing'), (4, 'Account sharing'), (5, 'Other')], default=1)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('banned', models.GenericIPAddressField()),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Address ban',
                'verbose_name_plural': 'IP Address bans',
                'db_table': 'ip_bans',
            },
        ),
        migrations.CreateModel(
            name='PlayerBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('permament', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(blank=True, default=apps.server.models.default_ban_length, null=True)),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Cheating'), (2, 'Racist'), (3, 'Swearing'), (4, 'Account sharing'), (5, 'Other')], default=1)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('banned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_player', to='players.Player')),
            ],
            options={
                'db_table': 'player_bans',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('type', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('record', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('key', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'storage',
            },
        ),
    ]
