# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpBans',
            fields=[
                ('ip', models.IntegerField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('banned_at', models.BigIntegerField()),
                ('expires_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ip_bans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.IntegerField()),
                ('itemtype', models.IntegerField()),
                ('amount', models.SmallIntegerField()),
                ('price', models.IntegerField()),
                ('expires_at', models.BigIntegerField()),
                ('inserted', models.BigIntegerField()),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'market_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.IntegerField()),
                ('itemtype', models.IntegerField()),
                ('amount', models.SmallIntegerField()),
                ('created', models.BigIntegerField()),
                ('anonymous', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'market_offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayersOnline',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'players_online',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('config', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'server_config',
                'managed': False,
            },
        ),
    ]
