# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddressban',
            options={'verbose_name': 'IP address ban', 'verbose_name_plural': 'IP address bans'},
        ),
    ]
