# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('warnings', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('rent', models.IntegerField()),
                ('town_id', models.IntegerField()),
                ('bid', models.IntegerField()),
                ('bid_end', models.IntegerField()),
                ('last_bid', models.IntegerField()),
                ('highest_bidder', models.IntegerField()),
                ('size', models.IntegerField()),
                ('beds', models.IntegerField()),
            ],
            options={
                'db_table': 'houses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listid', models.IntegerField()),
                ('list', models.TextField()),
            ],
            options={
                'db_table': 'house_lists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TileStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'tile_store',
                'managed': False,
            },
        ),
    ]
