# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('paid', models.PositiveIntegerField(default=0)),
                ('warnings', models.PositiveSmallIntegerField(default=0)),
                ('last_warning', models.DateTimeField(blank=True, default=None, null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_owner', to='players.Player')),
            ],
            options={
                'db_table': 'houses',
            },
        ),
        migrations.CreateModel(
            name='HouseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField(default=0)),
                ('list', models.TextField(blank=True, default='', max_length=1000)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
            ],
            options={
                'db_table': 'house_lists',
            },
        ),
        migrations.CreateModel(
            name='HouseTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('z', models.PositiveSmallIntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
            ],
            options={
                'db_table': 'house_tiles',
            },
        ),
        migrations.CreateModel(
            name='HouseTileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(db_index=True)),
                ('p_id', models.IntegerField(default=0)),
                ('item_type', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
                ('attributes', models.BinaryField(default=b'')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.HouseTile')),
            ],
            options={
                'db_table': 'house_tileitems',
            },
        ),
        migrations.AlterUniqueTogether(
            name='housetileitem',
            unique_together=set([('tile', 's_id')]),
        ),
        migrations.AlterIndexTogether(
            name='housetile',
            index_together=set([('x', 'y', 'z')]),
        ),
        migrations.AlterUniqueTogether(
            name='houselist',
            unique_together=set([('house', 'list_id')]),
        ),
    ]
